import datetime

from config.chroma import AUTHOR
import config.logging
from config.training import MODEL
from logger.helper import timed_block
from logger.setup import LoggerHandler
from storage_utils.db_hanler import CQCollectionHandler, DocumentCollectionHandler, GACollectionHandler
from training.generator import ContextualizedQuestionGenerator


log_handler = LoggerHandler(
    folder_path=config.logging.FOLDER_PATH,
    max_file_size=config.logging.MAX_SIZE,
    backup_count=config.logging.MAX_NUM_FILE,
    console_level=config.logging.CONSOLE_LEVEL,
    file_level=config.logging.FILE_LEVEL,
    console_message_format=config.logging.CONSOLE_MESSAGE_FORMAT,
    console_date_format=config.logging.CONSOLE_DATE_FORMAT,
    file_date_format=config.logging.FILE_DATE_FORMAT,
    force_new_instance=True
)
log_handler.setup(namespace="training_pipeline")
logger = log_handler.get_logger("training_pipeline")

def run():
    logger.info(f"{chr(0x1F3C3)} The model training pipeline is executed.")

    # ChromaDB collection handlers
    documents_handler = DocumentCollectionHandler()  # `documents` collction
    cq_handler = CQCollectionHandler(
        metadata={
            "description": (
                f"Questions generated by the {MODEL} model with related "
                "information to retrieve context origin."),
            "created": str(datetime.datetime.now()),
            "author": AUTHOR
        }
    )  # `contextual_questions` collction
    ga_handler = GACollectionHandler(
        metadata={
            "description": (
                f"Responses generated by the {MODEL} model in response to "
                "contextualised questions, with associated information to retrieve "
                "the source of the context."),
            "created": str(datetime.datetime.now()),
            "author": AUTHOR
        }
    )  # `generated_answers` collction

    # AI contextualized question generator
    cq_generator = ContextualizedQuestionGenerator()

    with timed_block(f"Processing of the contextualized question-answer pairs took", logger):
        for batch_i, chunks_batch in enumerate(documents_handler.walk(20)):

            docs = chunks_batch['documents']
            if not docs:
                logger.warning(
                    f"No textual chunk could be retrieved from the '{documents_handler.name}' collection.")
                return

            ids = chunks_batch['ids']
            step = max(1, int(len(ids) * 0.2))  # Log about every 20% of completion
            for i, (cur_chunk_id, cur_chunk_text) in enumerate(zip(ids, docs)):
                try:
                    contextual_questions_answers = cq_generator.generate(
                        prompt_context=cur_chunk_text,
                        context_id=cur_chunk_id
                    )

                    if contextual_questions_answers is None:
                        logger.warning(f"No question-answer pairs were generated.")
                    else:
                        cq_handler.add_entry(contextual_questions_answers)
                        ga_handler.add_entry(contextual_questions_answers)
                except Exception as e:
                    logger.error(f"Error processing chunk {cur_chunk_id}: {e}")

                if (i + 1) % step == 0:
                    progress = (i + 1) / len(ids) * 100
                    logger.debug(
                        f"Processed {progress:.0f}% of batch number {batch_i}."
                    )

    logger.info("Pipeline successfully executed.")