from functools import lru_cache
import itertools
import re
from typing import Any, Dict, List, Literal, Optional, Tuple, Union

from bs4 import BeautifulSoup
import contractions
from huggingface_hub.utils.logging import disable_propagation
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import sent_tokenize, word_tokenize, TreebankWordDetokenizer
from nltk import pos_tag
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import spacy
import spacy.tokens
from textblob import TextBlob
from transformers import pipeline, BartForConditionalGeneration, BartTokenizer

from config.embedding import FIXED_EMBEDDING_LENGTH, MODEL_SENTENCE_TRANSFORMER
from config.processing_text import (
    INSTALL_MISSING_NLTK,
    MIN_CHUNK_LENGTH,
    STEPS,
    SUMMARIZATION
)
from logger.helper import timed_block
from logger.setup import LoggerHandler
from text.components import Document, Page, TextBlock


disable_propagation()
logger = LoggerHandler().get_logger(__name__)

class TextProcessor:
    """A class for processing text data, including cleaning, summarizing,
    tokenization, and embedding generation.

    Parameters
    ----------
    model_name : str, optional
        The name of the SentenceTransformer model to use for embedding
        generation.
    fixed_length : Optional[int], optional
        The fixed length for truncating embeddings, if specified.
    apply_summarization : bool, optional
        Whether to generate the full page summary.

    Attributes
    ----------
    special_char_pat : Pattern
        Regex pattern to identify special characters.
    extra_spaces_pat : Pattern
        Regex pattern to identify extra spaces.
    digits_pat : Pattern
        Regex pattern to identify digits.
    url_pat : Pattern
        Regex pattern to identify URLs.
    email_pat : Pattern
        Regex pattern to identify email addresses.
    nlp : spacy.Language
        SpaCy language model for text processing.
    embedder_model : SentenceTransformer
        Model for generating sentence embeddings.
    summary_is_active : bool
        Indicates if summarization is active.
    bart_model : BartForConditionalGeneration
        The pre-trained BART model. Only available when
        `summary_is_active=True`.
    bart_tok : BartTokenizer
        The BART tokenizer. Only available when `summary_is_active=True`.
    summarizer : Callable
        Pre-trained summarization model. Only available when
        `summary_is_active=True`.
    embedding_size : int
        Size of the embeddings generated by the embedder model.
    FAST_FORWARD_PROCEDURES : Dict[str, Callable]
        Dictionary mapping fast-forward procedure names to their
        corresponding methods.
    IN_DEPTH_PROCEDURES : Dict[str, Callable]
        Dictionary mapping in-depth procedure names to their
        corresponding methods.
    fast_forward : Dict[str, bool]
        Configuration for fast-forward processing steps.
    in_depth : Dict[str, bool]
        Configuration for in-depth processing steps.
    ff_is_active : bool
        Indicates if fast-forward processing is active.
    id_is_active : bool
        Indicates if in-depth processing is active.
    synonym_replacement_available : bool
        Indicates if synonym replacement is available.

    Methods
    -------
    `clean_text(text: str, chunk_length: int)` -> str
        Clean the input text by converting it to lowercase and removing
        special characters.
    `summarize_text(text: str, max_length: int, min_length: int)` -> str
        Summarize the input text using a pre-trained summarization model.
    `remove_stopwords(text: str | spacy.tokens.Doc, lemmatization: bool)` -> str
        Remove stopwords and, if required, lemmatise tokens.
    `lemmatize(text: str | spacy.tokens.Doc)` -> str
        Lemmatize the input text tokens.
    `remove_urls_emails(text: str)` -> str
        Remove URLs and email addresses from the input text.
    `remove_html_tags(text: str)` -> str
        Remove HTML tags from the input text.
    `expand_contractions(text: str)` -> str
        Expand contractions in the input text.
    `remove_digits(text: str)` -> str
        Remove all digit characters from the input text.
    `correct_spelling(text: str)` -> str
        Correct spelling errors in the input text.
    `replace_synonym(text: str)` -> str
        Replace each word in the input text with its most common synonym
        using WordNet.
    `smart_lowercase(text: str | spacy.tokens.Doc)` -> str
        Convert text to lowercase, preserving proper nouns.
    `filter_out_named_entities(text: str | spacy.tokens.Doc)` -> str
        Filter out named entities from the input text.
    `remove_extra_spaces(text: str)` -> str
        Remove extra spaces from the input text.
    `process_text(file: Document)` -> None
        Apply all pre-processing steps in the order specified in the
        configuration.
    `compute_embedding(file: Document)` -> None
        Compute the embeddings of the processed text chunks using the
        `SentenceTransformer` model.
    """

    sentence_pat = re.compile(r'(?<=[.?!])\s+')
    special_char_pat = re.compile(r'[^a-z0-9. ]')
    extra_spaces_pat = re.compile(r'\s+')
    digits_pat = re.compile(r'\d+')
    url_pat = re.compile(r'https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+|www\.\S+', re.IGNORECASE)
    email_pat = re.compile(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', re.IGNORECASE)

    def __init__(
            self,
            model_name: Optional[str] = MODEL_SENTENCE_TRANSFORMER,
            fixed_length: Optional[int] = FIXED_EMBEDDING_LENGTH,
            apply_summarization: bool = SUMMARIZATION["active"]
        ) -> None:
        try:
            self.nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])
        except Exception as e:
            logger.error(f"Error loading model `en_core_web_sm`: {e}")
            raise

        try:
            self.embedder_model = SentenceTransformer(
                model_name,
                truncate_dim = fixed_length
            )
        except Exception as e:
            logger.error(f"Error during instantiation of SentenceTransformer: {e}")
            raise

        self.summary_is_active = apply_summarization

        @lru_cache(maxsize=1)
        def get_summarizer():
            return pipeline(
                "summarization",
                model=self.bart_model,
                tokenizer=self.bart_tok,
                framework="pt"
            )

        if self.summary_is_active:
            self._retrieve_bart()
            try:
                self.summarizer = get_summarizer()
                logger.debug(
                    "Summary for the content of the pages will also be generated.")
            except Exception as e:
                logger.error(
                    f"Error during instantiation of summary pipeline: {e}")
                raise

        self.embedding_size = self.embedder_model.get_sentence_embedding_dimension() or 384

        self._init_procedures()

        logger.debug(
            f"Successfully initialised the {self.__class__.__name__} instance.")

    def clean_text(
            self,
            text: str,
            chunk_length: Optional[int] = MIN_CHUNK_LENGTH
        ) -> str:
        """Clean the input text by converting it to lowercase and removing
        special characters. If a minimum length has been specified
        (`chunk_length != None`) and the processed text is less than it,
        return an empty string.
        """
        if (isinstance(chunk_length, int) and chunk_length <= 0 or
            not isinstance(chunk_length, int) and chunk_length is not None):
            logger.error(
                ("The minimum length of the chunks must be a positive integer. "
                f"Instead, {chunk_length} has been provided."))
            raise ValueError("`chunk_length` must be a positive integer")

        text = self._validate_text(
            text, method_name="clean_text", expected_type=str) # type: ignore
        if not text:
            return ""

        # Identify any character in a string that is not a lowercase
        # letter, number or space (only spaces, no tabs or newline
        # characters), such as punctuation, special symbols or capital
        # letters.
        cleaned = self.special_char_pat.sub(' ', text.lower())

        # Replace multiple spaces with a single space & strip
        # leading/trailing spaces
        cleaned = self.remove_extra_spaces(cleaned)

        if chunk_length and len(cleaned) <= chunk_length:
            return ""
        return cleaned

    def summarize_text(
            self,
            text: str,
            max_length: int = SUMMARIZATION["maxSummaryLength"],
            min_length: int = SUMMARIZATION["minSummaryLength"]
        ) -> str:
        """Summarize the input text using a pre-trained summarization model.

        Parameters
        ----------
        text : str
            The text to be summarized.
        max_length : int, optional
            The maximum length of the summary, default is MAX_SUMMARY_LENGTH.
        min_length : int, optional
            The minimum length of the summary, default is MIN_SUMMARY_LENGTH.

        Returns
        -------
        str
            The summarized text.

        Raises
        ------
        ValueError
            If the maximum length is less than the minimum length or if
            either length is not a positive integer.
        """
        if not text:
            return ""

        if max_length < min_length:
            logger.error(
                "The maximum length of the summary must be greater than the minimum length.")
            raise ValueError(
                f"Maximum length less than minimum length: {max_length} < {min_length}")
        if (not isinstance(max_length, int) or
            not isinstance(min_length, int) or
            max_length < 0 or min_length < 0):
            logger.error(
                "The minimum and maximum length of the summary must be positive integers.")
            raise ValueError("Invalid minimum or maximum length")

        logger.debug(
            "Input text length: {}; Number of tokens: {}".format(
                len(text),
                len(self.bart_tok.encode(text, add_special_tokens=False))
            )
        )
        if max_length > len(text):
            max_length = len(text)//2
            logger.warning(
                "Length of text less than the maximum length required; half "
                f"the length of the text ({max_length}) is used as the maximum length."
            )
        if max_length < min_length:
            min_length = len(text)//3
            logger.warning(
                "Minimum length is greater than the maximum length required; one third of "
                f"the length of the text ({min_length}) is used as the minimum length."
            )

        try:
            # summary = self.summarizer(
            #     text,
            #     max_length=max_length,
            #     min_length=min_length,
            #     do_sample=False,
            #     # truncation=True
            # )
            # return summary[0]['summary_text'] # type: ignore
            inputs = self.bart_tok.encode(
                "summarize: " + text,
                return_tensors="pt",
                max_length=1024,
                truncation=True
            )
            summary_ids = self.bart_model.generate(
                inputs,
                max_length=max_length,
                min_length=min_length,
                length_penalty=2.0,
                num_beams=4,
                early_stopping=True
            )

            summary = self.bart_tok.decode(summary_ids[0], skip_special_tokens=True)
            return summary
        except ValueError as e:
            logger.error(f"Value error during text summarization: {e}")
            return ""
        except RuntimeError as e:
            logger.error(f"Runtime error during text summarization: {e}")
            return ""
        except Exception as e:
            logger.exception(f"Error during text summarization: {e}", stack_info=True)
            # return ""
            raise

    def remove_stopwords(
            self,
            text: Union[str, spacy.tokens.Doc],
            lemmatization: bool
        ) -> str:
        """Remove stopwords and, if required, lemmatise tokens."""
        text = self._validate_text(
            text,
            method_name="remove_stopwords",
            expected_type=(str, spacy.tokens.Doc)
        )
        if not text:
            return ""

        if isinstance(text, str):
            text = self.nlp(text)

        tokens = (token.lemma_ if lemmatization else token.text for token in text if not token.is_stop)
        return " ".join(tokens)

    @lru_cache(maxsize=None)
    def lemmatize(self, text: Union[str, spacy.tokens.Doc]) -> str:
        """Lemmatise the input text tokens."""
        text = self._validate_text(
            text,
            method_name="lemmatize",
            expected_type=(str, spacy.tokens.Doc)
        )
        if not text:
            return ""

        if isinstance(text, str):
            text = self.nlp(text)

        return " ".join(token.lemma_ for token in text)

    def remove_urls_emails(self, text: str) -> str:
        """Remove URLs and email addresses from the input text."""
        text = self._validate_text(
            text, method_name="remove_urls_emails", expected_type=str) # type: ignore
        if not text:
            return ""

        text = self.url_pat.sub('', text)  # URLs
        text = self.email_pat.sub('', text)  # Emails
        return text

    def remove_html_tags(self, text: str) -> str:
        """Remove HTML tags from the input text."""
        text = self._validate_text(
            text, method_name="remove_html_tags", expected_type=str) # type: ignore
        if not text:
            return ""

        try:
            return BeautifulSoup(text, "html.parser").get_text().strip()
        except Exception as e:
            logger.error(f"Error parsing HTML: {e}", exc_info=True)
            return ""

    def expand_contractions(self, text: str) -> str:
        """Expand contractions in the input text."""
        text = self._validate_text(
            text, method_name="expand_contractions", expected_type=str) # type: ignore
        if not text:
            return ""

        try:
            return contractions.fix(text, slang=True) # type: ignore
        except Exception as e:
            logger.error(f"Error expanding contractions: {e}", exc_info=True)
            return text

    def remove_digits(self, text: str) -> str:
        """Remove all digit characters from the input text."""
        text = self._validate_text(
            text, method_name="remove_digits", expected_type=str) # type: ignore
        if not text:
            return ""

        return self.digits_pat.sub('', text)
        # return ''.join(char for char in text if not char.isdigit())

    @lru_cache(maxsize=None)
    def correct_spelling(self, text: str) -> str:
        text = self._validate_text(
            text, method_name="correct_spelling", expected_type=str) # type: ignore
        if not text:
            return ""

        try:
            return str(TextBlob(text).correct())
        except Exception as e:
            logger.error(
                f"Error during spelling correction: {e}", exc_info=True)
            return text

    def replace_synonym(self, text: str) -> str:
        """Replace each word in the input text with its most common synonym using WordNet."""
        text = self._validate_text(
            text, method_name="replace_synonym", expected_type=str) # type: ignore

        if not self.synonym_replacement_available:
            return text

        if not text:
            return ""

        @lru_cache(maxsize=None)
        def get_most_common_synonym(word: str, pos: str) -> str:
            """Retrieve the most common synonym for `word` considering its part of speech."""
            pos_map = {"N": wordnet.NOUN, "V": wordnet.VERB, "J": wordnet.ADJ, "R": wordnet.ADV}
            wn_pos = pos_map.get(pos[0].upper(), wordnet.NOUN)  # Default to NOUN

            synonyms = wordnet.synsets(word, wn_pos)
            if synonyms:
                # Handle multi-word synonyms
                synonym = synonyms[0].lemmas()[0].name().replace("_", " ")  # type: ignore
                return synonym.capitalize() if word.istitle() else synonym

            # Return original if no synonym found
            return word

        words = word_tokenize(text)
        words_with_pos = pos_tag(words)

        replaced_words = [get_most_common_synonym(word, pos) for word, pos in words_with_pos]

        # Detokenizer to correctly place punctuation
        return TreebankWordDetokenizer().detokenize(replaced_words)

    def smart_lowercase(self, text: Union[str, spacy.tokens.Doc]) -> str:
        """Convert text to lowercase, preserving proper nouns."""
        text = self._validate_text(
            text,
            method_name="smart_lowercase",
            expected_type=(str, spacy.tokens.Doc)
        )
        if not text:
            return ""

        if isinstance(text, str):
            text = self.nlp(text)

        return " ".join(
            (token.text if token.pos_ == "PROPN" else token.text.lower()
             for token in text)
        )

    def filter_out_named_entities(
            self,
            text: Union[str, spacy.tokens.Doc]
        ) -> str:
        """Filter out named entities from the input text."""
        text = self._validate_text(
            text,
            method_name="filter_out_named_entities",
            expected_type=(str, spacy.tokens.Doc)
        )
        if not text:
            return ""

        if isinstance(text, str):
            text = self.nlp(text)

        return " ".join((token.text for token in text if not token.ent_type_))

    def remove_extra_spaces(self, text: str) -> str:
        """Remove extra spaces from the input text."""
        text = self._validate_text(
            text, method_name="remove_extra_spaces", expected_type=str) # type: ignore
        if not text:
            return ""

        return self.extra_spaces_pat.sub(' ', text).strip()

    def chunk_text(self, text: str, threshold: int = 80) -> List[str]:
        """Divide the input text into chunks based on sentence similarity.

        Parameters
        ----------
        text : str
            The text to be chunked.
        threshold : int, optional
            The percentile threshold for determining chunk breakpoints,
            default is 80.

        Returns
        -------
        List[str]
            A list of text chunks, where each chunk is a group of
            sentences with high similarity.

        Notes
        -----
        The algorithm involves dividing a given text into semantically
        meaningful chunks using vector embeddings and cosine similarity.

        First, the text is broken down into sentences, which are
        converted into vector embeddings.
        Instead of computing cosine similarity between consecutive
        sentences, each sentence is grouped with its neighboring
        sentences (previous and following) before computing similarity.
        This improves segmentation by capturing contextual meaning
        across sentence boundaries.

        A threshold (e.g., 0.8) determines the division of groups: when
        the similarity between two consecutive groups exceeds this
        value, a new group begins. This method helps preserve context
        and improves chunking accuracy.
        """
        if not text:
            return []

        # Tokenize into sentences
        single_sentences = sent_tokenize(text) # self.sentence_pat.split(text)

        # Combine adjacent sentences to improve contextual grouping
        combined_sentences = self._combine_sentences_with_context(single_sentences)
        
        # Compute vector embeddings in batch
        embeddings = self._text_to_vector(combined_sentences)
        
        # Compute pairwise cosine distances
        distances = self._consecutive_cosine_distances(embeddings)
        
        # Compute dynamic threshold (80th percentile)
        threshold_distance = np.percentile(distances, threshold)

        # Find breakpoints where similarity drops below the threshold
        indices_above_thr = np.argwhere(distances > threshold_distance).flatten()

        # Group sentences into chunks
        chunks, current_chunk = [], []
        for i, sentence in enumerate(single_sentences):
            current_chunk.append(sentence)
            if i in indices_above_thr:  # Split at breakpoints
                chunks.append(' '.join(current_chunk))
                current_chunk = []

        # Ensure last chunk is included
        if current_chunk:
            chunks.append(' '.join(current_chunk))

        return chunks

    def process_page_text(self, page: Page) -> None:
        """Process the textual content of a given page by applying
        *fast-forward* or *in-dept* text processing procedures,
        depending on the active configuration, and optionally
        summarizing the content  of the entire page, if summarization is
        active.
        """
        logger.debug(
            f"Text processing of page {page.number} of the current document.")

        step = int(len(page) * 0.2)  # Log about every 20% of completion
        for par_i, par in enumerate(page.paragraphs):

            if bool(par.processed_content):
                # Text processing for this chunk has already been done
                logger.warning("Chunk already processed; it is skipped.")
                continue

            processed_text = par.raw_content
            if self.ff_is_active:
                processed_text = self._apply_fast_forward_procedures(par.raw_content)
            elif self.id_is_active:
                processed_text = self._apply_in_depth_procedures(par.raw_content)

            par.processed_content = processed_text

            if step != 0 and (par_i + 1) % step == 0:
                progress = (par_i + 1) / len(page) * 100
                logger.debug(
                    f"{progress:.0f}% of page {page.number} text processing completed."
                )

        if self.summary_is_active:
            page.full_text.summarized_content = self.summarize_text(
                page.full_text.raw_content)

        logger.debug(f"Page {page.number} successfully processed.")

    def compute_paragraph_embedding(self, page: Page) -> None:
        """Compute embeddings for each paragraph in a given page using
        the SentenceTransformer model.
        """
        logger.debug(
            f"Generation of the embedding of page {page.number} of the current document.")

        with timed_block(f"Embedding generation for page {page.number} took", logger):

            step = int(len(page) * 0.22)  # Log about every 22% of completion
            for par_i, par in enumerate(page.paragraphs):

                if par.processed_content:
                    par.embedding = self._text_to_vector(
                        par.processed_content)[0].tolist()

                if step != 0 and (par_i + 1) % step == 0:
                    progress = (par_i + 1) / len(page) * 100
                    logger.debug(
                        f"{progress:.0f}% of the embeddings generation completed.")

    def document_semnantic_chunking(self, file: Document) -> None:
        """Chunk the text content of a document into smaller text
        blocks. It then generates embedding of the determined chunks of
        text."""
        logger.debug(
            f"Text chunking of the file `{file.metadata.file_name}` has begun.")

        with timed_block(f"Document chunking took", logger):
            # full_text = "\n".join(page.full_text.raw_content for page in file.pages)
            file.chunks = [
                TextBlock(id=str(i), content=chunk)
                for i, chunk in enumerate(self.chunk_text(file.full_text))
            ]
            logger.debug(f"Number of chunks created: {len(file.chunks)}")

            for chunk in file.chunks:
                if chunk.raw_content:
                    chunk.embedding = self._text_to_vector(
                        chunk.raw_content)[0].tolist()

        logger.debug("The chunking of the current document has been completed.")

    def process_document(self, file: Document) -> None:
        """Process a document by applying text processing and embedding
        generation to each page, followed by document chunking.
        """
        logger.info(f"Processing of the `{file.metadata.file_name}` file started.")

        with timed_block(f"Document processing and embedding generation took", logger):
            for page in file.pages:
                self.process_page_text(page)
                self.compute_paragraph_embedding(page)

        self.document_semnantic_chunking(file)

        logger.info(
            "Processing of current document content successfully completed.")

    def _validate_text(
            self,
            text: Union[str, spacy.tokens.Doc],
            method_name: str,
            expected_type: Union[type, Tuple[type, ...]]
        ) -> Union[str, spacy.tokens.Doc]:
        """Validate the type of the input text.

        Parameters
        ----------
        text : Union[str, spacy.tokens.Doc]
            The text to be validated.
        method_name : str
            The name of the method where the validation is performed.
        expected_type : Union[type, Tuple[type, ...]]
            The expected type(s) for the text.

        Returns
        -------
        Union[str, spacy.tokens.Doc]
            The validated text if it matches the expected type.

        Raises
        ------
        TypeError
            If the text is not of the expected type.
        """
        try:
            expected_types = (
                "' or '".join((t.__name__ for t in expected_type))
                if isinstance(expected_type, tuple) else expected_type.__name__
            )
            if not isinstance(text, expected_type):
                logger.error(
                    (f"Invalid input type for `text` in `{method_name}` method. "
                    f"Expected '{expected_types}', got '{type(text).__name__}'."))
                raise TypeError(f"Input must be of type '{expected_types}'")
            return text
        except Exception as e:
            logger.error(
                f"Exception occurred during text validation in `{method_name}`: {e}",
                exc_info=True
            )
            raise

    @lru_cache(maxsize=1)
    def _retrieve_bart(self) -> None:
        """Retrieve and cache the BART model and tokenizer."""
        try:
            if not hasattr(self, 'bart_model') or not self.bart_model:
                self.bart_model = BartForConditionalGeneration.from_pretrained(
                    SUMMARIZATION["modelName"])
            if not hasattr(self, 'bart_tok') or not self.bart_tok:
                self.bart_tok = BartTokenizer.from_pretrained(
                    SUMMARIZATION["modelName"])
        except Exception as e:
            logger.error(f"Error loading BART model or tokenizer: {e}")
            raise

    def _init_procedures(self, force_installation: bool = INSTALL_MISSING_NLTK) -> None:
        """Initialize text processing procedures for fast-forward and in-depth modes.

        This method sets up dictionaries mapping procedure names to their
        corresponding methods for both fast-forward and in-depth text
        processing. It retrieves the configuration for each mode from the
        `STEPS` dictionary and validates the procedures. If both modes are
        activated, a warning is logged, and the fast-forward procedure is
        applied by default.
        """
        self.FAST_FORWARD_PROCEDURES = {
            "cleanUpText": self.clean_text,
        }
        self.IN_DEPTH_PROCEDURES = {
            "urlEmailRemoval": self.remove_urls_emails,
            "htmlTagRemoval": self.remove_html_tags,
            "contractionExpansion": self.expand_contractions,
            "digitsRemoval": self.remove_digits,
            "handlingSpellingErrors": self.correct_spelling,
            "synonymReplacement": self.replace_synonym,
            "smartLowercasing": self.smart_lowercase,
            "entityMasking": self.filter_out_named_entities,
            "stopWordsRemoval": lambda text: self.remove_stopwords(
                text, lemmatization=False),
            "wordLemmatization": self.lemmatize,
            "extraWhitespacesRemoval": self.remove_extra_spaces,
            "cleanUpText": self.clean_text,
        }
        self.fast_forward = STEPS.get("fastForward", {})
        self.in_depth = STEPS.get("inDepth", {})

        self._validate_procedures(
            self.fast_forward, self.FAST_FORWARD_PROCEDURES, "fastForward")
        self._validate_procedures(
            self.in_depth, self.IN_DEPTH_PROCEDURES, "inDepth")

        self.ff_is_active = any(self.fast_forward.values())
        self.id_is_active = any(self.in_depth.values())

        if not self.ff_is_active and  not self.id_is_active:
            logger.warning(
                "No procedure was activated neither `fastForward` nor `inDepth`.")
        else:
            if self.ff_is_active and self.id_is_active:
                logger.warning(
                    ("Both the `fastForward` and `inDepth` procedures have been "
                    "activated, but only one of them can be applied. The "
                    "`fastForward` procedure is applied.")
                )
                self.id_is_active = False

            logger.debug(
                "Text is processed through the `{}` procedure(s): '{}'.".format(
                    "fastForward" if self.ff_is_active else "inDepth",
                    "', '".join(list(self.fast_forward.keys()))
                    if self.ff_is_active else "', '".join(list(self.in_depth.keys()))
            ))

        self._check_nltk_dependencies(force_installation)

    def _check_nltk_dependencies(self, force_installation: bool) -> None:
        """
        Check and ensure the availability of required NLTK resources.

        This method verifies the presence of the WordNet corpus, Punkt
        tokenizer, and averaged perceptron tagger. If any of these
        resources are missing, it attempts to download them if
        `force_installation` is True. Otherwise, it logs a warning and
        sets `synonym_replacement_available` to False.

        Parameters
        ----------
        force_installation : bool
            If True, missing NLTK resources will be automatically
            downloaded.
        """
        # Check if wordnet is available
        self.synonym_replacement_available = True
        try:
            wordnet.ensure_loaded()
        except LookupError:
            if force_installation:
                logger.warning(
                    "The Wordnet corpus is not available, so it is downloaded.")
                nltk.download('wordnet')
            else:
                logger.warning(
                    "Wordnet corpus is not available. Please download it using nltk.download('wordnet')."
                )
                self.synonym_replacement_available = False

        # Check if 'punkt' is available
        try:
            nltk.data.find('tokenizers/punkt')
        except LookupError:
            if force_installation:
                logger.warning(
                    "The Punkt data is not available, so it is downloaded.")
                nltk.download('punkt')
            else:
                logger.warning(
                    "Punkt data is not available. Please download it using nltk.download('punkt')."
                )
                self.synonym_replacement_available = False

        # Check if 'punkt' is available
        try:
            nltk.data.find('taggers/averaged_perceptron_tagger_eng')
        except LookupError:
            if force_installation:
                logger.warning(
                    "Tagger data is not available, so it is downloaded.")
                nltk.download('averaged_perceptron_tagger_eng')
            else:
                logger.warning(
                    "Tagger data is not available. Please download it using nltk.download('averaged_perceptron_tagger_eng')."
                )
                self.synonym_replacement_available = False

    def _validate_procedures(
            self,
            procedures: Dict[str, Any],
            valid_procedures: Dict[str, Any],
            procedure_type: Literal["fastForward", "inDepth"]
        ) -> None:
        """Validate the provided procedures against the valid procedures.

        Parameters
        ----------
        procedures : Dict[str, Any]
            The procedures to be validated.
        valid_procedures : Dict[str, Any]
            The dictionary of valid procedures.
        procedure_type : Literal["fastForward", "inDepth"]
            The type of procedure being validated.

        Raises
        ------
        KeyError
            If any procedure in `procedures` is not found in
            `valid_procedures`.
        """
        err = set(procedures) - set(valid_procedures)
        if err:
            logger.error(
                (f"`{procedure_type}` procedures can only be '{"', '".join(valid_procedures)}'. "
                 f"Instead, {', '.join(err)} were also provided.")
            )
            raise KeyError(f"Invalid procedure(s): {', '.join(err)}")

    def _apply_fast_forward_procedures(self, text: str) -> str:
        for name, is_active in self.fast_forward.items():
            if (is_active and
                name in self.FAST_FORWARD_PROCEDURES and
                name != "summarization"):
                text = self.FAST_FORWARD_PROCEDURES[name](text)
        return text

    def _apply_in_depth_procedures(self, text: str) -> str:
        for name, is_active in self.in_depth.items():
            if (is_active and
                name in self.IN_DEPTH_PROCEDURES and
                name != "summarization"):
                text = self.IN_DEPTH_PROCEDURES[name](text)
        return text

    def _text_to_vector(self, texts: Union[str, List[str]]) -> np.ndarray:
        """Convert input text (single string or list of sentences) into vector embeddings.

        Parameters
        ----------
        texts : str or List[str]
            Single sentence or list of sentences to be converted into
            embeddings.

        Returns
        -------
        np.ndarray
            A 2D NumPy array where each row represents an embedding vector.
        """
        if isinstance(texts, str):  # Convert single string into a list
            texts = [texts]

        if not texts:
            return np.zeros((1, self.embedding_size))

        try:
            return self.embedder_model.encode(
                sentences=texts,
                convert_to_tensor=False,
                show_progress_bar=False
            )
        except RuntimeError as e:
            logger.warning(f"Runtime error in embedding generation: {e}")
            return np.zeros((len(texts), self.embedding_size))

    def _combine_sentences_with_context(self, sentences: List[str]) -> List[str]:
        """Combine each sentence with its preceding and following
        sentences to provide additional context.
        """
        if not sentences:
            return []

        # If Python <3.10, use a manual alternative for pairwise
        prev_sents = [''] + sentences[:-1]  # Shift left (add empty for first)
        next_sents = sentences[1:] + ['']   # Shift right (add empty for last)

        return [
            f"{prev} {sent} {nxt}".strip()
            for prev, sent, nxt in zip(prev_sents, sentences, next_sents)
        ]

    def _consecutive_cosine_distances(
            self,
            embeddings: Union[np.ndarray, List[List[float]]]
        ) -> np.ndarray:
        """Compute cosine distances, defined as 1 minus the cosine
        similarity, between each pair of consecutive embeddings.
        """
        embeddings = np.asarray(embeddings)  # Ensure it's a NumPy array

        if embeddings.size == 0 or len(embeddings) < 2:
            return np.array([])  # Return empty NumPy array

        return 1 - cosine_similarity(embeddings[:-1], embeddings[1:]).diagonal()